# Site settings
title: Stefan Strahl
email: stef@nstrahl.de
url: https://strahl.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Neuroscientist - Hacker - Geek"
meta_author: Strahl Stefan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Stefan Strahl
  location: Göttingen, DE
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stefanstrahl
  - title: facebook
    url: https://www.facebook.com/stefan.strahl
  - title: stack-overflow
    url: http://stackoverflow.com/users/4278397/stefan-strahl
  - title: github
    url: http://github.com/strahl

# Postal address (add as many lines as necessary)
address:
  - line: Ampferweg 7
  - line: 37077 Göttingen
  - line: Germany

# Credits content
credits: 'Based on <a href="http://startbootstrap.com">Freelancer</a>.'

# Build settings
markdown: kramdown
permalink: pretty
